// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorAPI.Models
{
    public partial class Category
    {
        public Category()
        {
            IdO = new HashSet<Objects>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Objects> IdO { get; set; }
    }
}