// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BlazorAPI.Models
{
    public partial class NewTestDateBaseContext : DbContext
    {
        public NewTestDateBaseContext()
        {
        }

        public NewTestDateBaseContext(DbContextOptions<NewTestDateBaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>(entity =>
            {
                entity.Property(e => e.Name).IsRequired();
            });

            modelBuilder.Entity<Objects>(entity =>
            {
                entity.Property(e => e.Name).IsRequired();

                entity.HasMany(d => d.IdC)
                    .WithMany(p => p.IdO)
                    .UsingEntity<Dictionary<string, object>>(
                        "Key",
                        l => l.HasOne<Category>().WithMany().HasForeignKey("IdC").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__Key__Id_C__5812160E"),
                        r => r.HasOne<Objects>().WithMany().HasForeignKey("IdO").OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK__Key__Id_O__571DF1D5"),
                        j =>
                        {
                            j.HasKey("IdO", "IdC").HasName("PK__tmp_ms_x__1C07BE6D634CF62A");

                            j.ToTable("Key");

                            j.IndexerProperty<int>("IdO").HasColumnName("Id_O");

                            j.IndexerProperty<int>("IdC").HasColumnName("Id_C");
                        });
            });

            OnModelCreatingPartial(modelBuilder);
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Data Source=DESKTOP-6NJDOQP\SQLEXPRESS;Initial Catalog=NewTestDateBase;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
            }
        }
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}