// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorAPI.Models
{
    public partial class Objects
    {
        public Objects()
        {
            IdC = new HashSet<Category>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }

        public virtual ICollection<Category> IdC { get; set; }
    }
}